# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/af_kit',
                'doc_host': 'https://sky1ove.github.io',
                'git_url': 'https://github.com/sky1ove/af_kit',
                'lib_path': 'af_kit'},
  'syms': {'af_kit.core': {'af_kit.core.foo': ('core.html#foo', 'af_kit/core.py')}}}
